var aoPlayers = [
    {
        id: 0,
        name: "Player 1",
        avatar: "car",
        location: 0,
        dice: 0,
        credits: 1500,
        debt: [0, 0, 0, 0, 0, 0, 0],
        priority: 0,
        doubles: 0,
        jail: 0,
        cards: [0, 0],
        start: "yes",
        roll: "yes",
        buy: "no",
        pay: "no",
        chest: "no",
        chance: "no",
        redirect: "no"
    },
    {
        id: 1,
        name: "Player 2",
        avatar: "thimble",
        location: 0,
        dice: 0,
        credits: 1500,
        debt: [0, 0, 0, 0, 0, 0, 0],
        priority: 0,
        doubles: 0,
        jail: 0,
        cards: [0, 0],
        start: "yes",
        roll: "yes",
        buy: "no",
        pay: "no",
        chest: "no",
        chance: "no",
        redirect: "no"
    },
    {
        id: 2,
        name: "Player 3",
        avatar: "boat",
        location: 0,
        dice: 0,
        credits: 1500,
        debt: [0, 0, 0, 0, 0, 0, 0],
        priority: 0,
        doubles: 0,
        jail: 0,
        cards: [0, 0],
        start: "yes",
        roll: "yes",
        buy: "no",
        pay: "no",
        chest: "no",
        chance: "no",
        redirect: "no"
    },
    {
        id: 3,
        name: "Player 4",
        avatar: "dog",
        location: 0,
        dice: 0,
        credits: 1500,
        debt: [0, 0, 0, 0, 0, 0, 0],
        priority: 0,
        doubles: 0,
        jail: 0,
        cards: [0, 0],
        start: "yes",
        roll: "yes",
        buy: "no",
        pay: "no",
        chest: "no",
        chance: "no",
        redirect: "no"
    },
    {
        id: 4,
        name: "Player 5",
        avatar: "hat",
        location: 0,
        dice: 0,
        credits: 1500,
        debt: [0, 0, 0, 0, 0, 0, 0],
        priority: 0,
        doubles: 0,
        jail: 0,
        cards: [0, 0],
        start: "yes",
        roll: "yes",
        buy: "no",
        pay: "no",
        chest: "no",
        chance: "no",
        redirect: "no"
    },
    {
        id: 5,
        name: "Player 6",
        avatar: "cart",
        location: 0,
        dice: 0,
        credits: 1500,
        debt: [0, 0, 0, 0, 0, 0, 0],
        priority: 0,
        doubles: 0,
        jail: 0,
        cards: [0, 0],
        start: "yes",
        roll: "yes",
        buy: "no",
        pay: "no",
        chest: "no",
        chance: "no",
        redirect: "no"
    }
];